### ISSUE TITLE
No context menu in OS X

### ISSUE THREAD

**Issue by demidovakatya** [ekazyam/SidebarSeparator#11]
Failed to add separator via context menu. Ctrl+Shift+S works perfectly.

Please, add support of two-finger click for Mac users.

**Comment by ekazyam** [comment]
Oh,sorry.

But, I do not have now verifiable mac.
Please use the shortcut it until it can support.

Thank you for the report.

**Comment by demidovakatya** [comment]
If you are interested in this feature, contact me, I'll test it on my Mac. :santa:

**Comment by ekazyam** [comment]
Thanks.
First of all, I want to organize the problems.
What both current problems.
1.Right-click Add Separator context is not displayed in the folder listed in FOLDERS of Sidebar.
2.Add Separator context of right-click in the folder listed in FOLDERS of the Sidebar but is displayed, separator is not added to be selected Separator context.

**Comment by ekazyam** [comment]
Thanks.
First of all, I want to organize the problems.
What both current problems.
1.Right-click Add Separator context is not displayed in the folder listed in FOLDERS of Sidebar.
2.Add Separator context of right-click in the folder listed in FOLDERS of the Sidebar but is displayed, separator is not added to be selected Separator context.

**Comment by demidovakatya** [comment]
What do you mean by "organize the problems"?

**Comment by ekazyam** [comment]
It is mean you want to understand the situation in which the problem is occurring.

**Comment by demidovakatya** [comment]
right-click on any folder → context menu → success!

right-click on "FOLDERS", "FILES" or any file → nothing happens

Is it by design?

P.S.: It didn't work previous time, though. I reinstalled the plugin and restored all settings to default.

**Comment by ekazyam** [comment]
I understand.

>Is it by design?
>right-click on "FOLDERS", "FILES" or any file → nothing happens
Yes,because there is no API is sublime text.
I think a little strange that it issue a context menu on any folder,but that was the only way.

**Comment by ekazyam** [comment]
I understand.

> Is it by design?
> right-click on "FOLDERS", "FILES" or any file → nothing happens

Yes,because there is no API is sublime text.
I think a little strange that it issue a context menu on any folder,but that was the only way.

**Comment by demidovakatya** [comment]
yeh, that's strange.. sublime text is frustrating sometimes.

just in case – context menu screenshot. 
![menu-os-x](https://cloud.githubusercontent.com/assets/5788652/12047738/bcdd4800-aee1-11e5-9c2f-9c65fbcd47da.png)

thanks for answering and creating the package!
