### ISSUE TITLE
ST3 Bug - Ctrl+Shift+S causes nav tabs to disappear

### ISSUE THREAD

**Issue by lunacodes** [ekazyam/SidebarSeparator#13]
### Summary

`Ctrl+Shift+S` causes nav tabs to disappear and `View -> Show Tabs` to stop functioning
### Expected behavior

`Ctrl+Shift+S` should `"Save As"`
### Actual behavior
- `Ctrl+Shift+S` causes tabs to disappear and creates a new tab that displays as  `===================`
- `View Tabs` menu item and `Toggle: View Tabs` command stop functioning
- Requires computer restart before functionality resumes.  Pressing `Ctrl+Shift+S` after computer restart still triggers issue.
### Steps to reproduce

Sorry - no idea :/

`sublime.log_commands(True)` shows command:sidebar_separate as the command called upon pressing `Ctrl+Shift+S`
### Workaround
- Restart Computer 
- Copy/Paste and save the `Ctrl+Shift+S` keybinding from Sublime's `Default Key Bindings` to the `User's Keybindings`
- Disabling the Package also resolves the issue
### Environment
- Operating system and version:
  - Windows 8
- Sublime Text:
  - Build 3103

**Comment by julien1441** [comment]
**Same issue.**

The nav tabs completly disappear and can't be recovered by _View >Show Tabs_.
Removing the package resolve the issue.

**How to solve:**
Remove the package.
Click _View >Show Tabs_.
Reinstall the package.
But, **(/!\)**before adding a separator**(/!\)**, put in _Preferences > Package Settings > SidebarSeparator > Settings - User_, the setting:

> "auto_tab_hide": false"

It resolve permanently the issue.

**Comment by lunacodes** [comment]
Good to know!!  I'd suggest making that change the default for the package.

I'm realizing now that it's in the Readme that you can change it, but somehow I missed that, and it seems like a strange assumption for a default behavior (to me anyway).

**Comment by ekazyam** [comment]
Thank you for contacting me.
Hard to see when you view the separator in the tab . Standard we have to like to hide the tab automatically.
There were suggestions for improvement . For this reason , we've implemented as one of the functions .
https://github.com/ekazyam/SidebarSeparator/issues/2

**Comment by lunacodes** [comment]
Hi!  Thanks for your response :)

Just to clarify, the issue we're experiencing is that `"auto_tab_hide": True` is currently causing _All_ of the tabs to disappear (not just the new tab that's mentioned in the issue you linked to)
